# Generated by Django 4.0.6 on 2022-07-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='coverart',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
